name: Build for Mac Intel

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: macos-15-intel
    
    steps:
    - uses: actions/checkout@master
      name: checkout
      
    - run: brew install qt@5
      name: Install Qt5 via Homebrew
      
    - run: export PATH="$(brew --prefix qt@5)/bin:$PATH" && ./scripts/build_macos_native.sh && mv build/bin/mac_arm64.zip build/bin/mac_intel.zip
      name: build-for-mac-intel
    - uses: actions/upload-artifact@master
      with:
         name: tsMuxer_mac_intel
         path: build/bin/mac_intel.zip
      name: upload-artefact
