name: Build for Mac

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: docker://justdan96/tsmuxer_build:latest
      volumes:
      - /workspace:/github/workspace
    
    steps:
    - uses: actions/checkout@master
      name: checkout
      
    - run: rm -f bin/.gitkeep
      name: clean-bin-folder
      
    - run: ./scripts/rebuild_osxcross_with_gui_docker.sh
      name: build-for-mac-intel
      
    - uses: actions/upload-artifact@master
      with:
         name: tsMuxer_mac_intel
         path: bin
      name: upload-artefact
